create table user
(
    user_id  integer generated by default as identity,
    name     varchar(255),
    surname  varchar(255),
    phone_nr varchar(255),
    email    varchar(255),
    address  varchar(255),
    password varchar(255),
    primary key (user_id)
);
insert into user values
    (1, 'Alan', 'Walker', '+37068957624', 'A.Walker@gmail.com', 'New York, Crowner St. 78, 888862', 'Alan?'),
    (2, 'Jonas', 'Kreivys', '+37012345678', 'jonas.kreivys@gmail.com', 'Kaunas, Laisvės al. 45, 45458', 'JKreivys123!@'),
    (3, 'Jonas', 'Jonaitis', '869857624', 'j.jonaitis@gmail.com', 'Vilnius, Laisvės pr. 456, 06444', 'JJonaitis321!'),
    (4, 'Petras', 'Antanaitis', '+37068957456', 'petras.a@yahoo.com', 'Trakai, Oslo g. 456, 87963', 'P@Antanaitis'),
    (5, 'Ona', 'Stasyte', '+77068957624', 'o.stas@mail.ru', 'Moscow, Malysheva ul. 7, 045556', 'OStas@@'),
    (6, 'Piotr', 'Vladimirov', '87068957624', 'p.vlad@mail.ru', 'Chelyabinsk, Rossiyskaya ul. 456, 045648', 'Piotr111@@@');