create table user
(
    user_id  integer generated by default as identity,
    address  varchar(255),
    email    varchar(255),
    name     varchar(255),
    password varchar(255),
    phone_nr varchar(255),
    surname  varchar(255),
    primary key (user_id)
);
insert into user values
    (1, 'Vilnius', 'google@gmail.com', 'Alan', 'alan', '+3700000000', 'Walker');